# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bcTx.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bcTx.proto',
  package='',
  serialized_pb='\n\nbcTx.proto\"\xa9\x02\n\x07\x42sTxMsg\x12*\n\tnRecvType\x18\x01 \x02(\x0e\x32\x11.BsTxMsg.recvtype:\x04\x46WJQ\x12!\n\x07\x66wjqMsg\x18\x02 \x01(\x0b\x32\x10.BsTxMsg.FwjqMsg\x12!\n\x07kfqqMsg\x18\x03 \x01(\x0b\x32\x10.BsTxMsg.KfqqMsg\x1aJ\n\x07\x46wjqMsg\x12\x19\n\x11nAuthenticationId\x18\x01 \x02(\r\x12\x11\n\tsQtsentid\x18\x02 \x02(\t\x12\x11\n\tnCategory\x18\x03 \x02(\r\x1a@\n\x07KfqqMsg\x12\x11\n\tsQtsentid\x18\x01 \x02(\t\x12\x11\n\tnCategory\x18\x02 \x02(\r\x12\x0f\n\x07nRecvid\x18\x03 \x02(\r\"\x1e\n\x08recvtype\x12\x08\n\x04\x46WJQ\x10\x01\x12\x08\n\x04KFQQ\x10\x02\"E\n\x07\x42sfkMsg\x12\x19\n\x11nAuthenticationId\x18\x01 \x02(\r\x12\x11\n\tsQtsentid\x18\x02 \x02(\t\x12\x0c\n\x04nRes\x18\x03 \x02(\r')



_BSTXMSG_RECVTYPE = _descriptor.EnumDescriptor(
  name='recvtype',
  full_name='BsTxMsg.recvtype',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FWJQ', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KFQQ', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=282,
  serialized_end=312,
)


_BSTXMSG_FWJQMSG = _descriptor.Descriptor(
  name='FwjqMsg',
  full_name='BsTxMsg.FwjqMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nAuthenticationId', full_name='BsTxMsg.FwjqMsg.nAuthenticationId', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sQtsentid', full_name='BsTxMsg.FwjqMsg.sQtsentid', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nCategory', full_name='BsTxMsg.FwjqMsg.nCategory', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=140,
  serialized_end=214,
)

_BSTXMSG_KFQQMSG = _descriptor.Descriptor(
  name='KfqqMsg',
  full_name='BsTxMsg.KfqqMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sQtsentid', full_name='BsTxMsg.KfqqMsg.sQtsentid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nCategory', full_name='BsTxMsg.KfqqMsg.nCategory', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nRecvid', full_name='BsTxMsg.KfqqMsg.nRecvid', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=216,
  serialized_end=280,
)

_BSTXMSG = _descriptor.Descriptor(
  name='BsTxMsg',
  full_name='BsTxMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nRecvType', full_name='BsTxMsg.nRecvType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fwjqMsg', full_name='BsTxMsg.fwjqMsg', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kfqqMsg', full_name='BsTxMsg.kfqqMsg', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_BSTXMSG_FWJQMSG, _BSTXMSG_KFQQMSG, ],
  enum_types=[
    _BSTXMSG_RECVTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=15,
  serialized_end=312,
)


_BSFKMSG = _descriptor.Descriptor(
  name='BsfkMsg',
  full_name='BsfkMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nAuthenticationId', full_name='BsfkMsg.nAuthenticationId', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sQtsentid', full_name='BsfkMsg.sQtsentid', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nRes', full_name='BsfkMsg.nRes', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=314,
  serialized_end=383,
)

_BSTXMSG_FWJQMSG.containing_type = _BSTXMSG;
_BSTXMSG_KFQQMSG.containing_type = _BSTXMSG;
_BSTXMSG.fields_by_name['nRecvType'].enum_type = _BSTXMSG_RECVTYPE
_BSTXMSG.fields_by_name['fwjqMsg'].message_type = _BSTXMSG_FWJQMSG
_BSTXMSG.fields_by_name['kfqqMsg'].message_type = _BSTXMSG_KFQQMSG
_BSTXMSG_RECVTYPE.containing_type = _BSTXMSG;
DESCRIPTOR.message_types_by_name['BsTxMsg'] = _BSTXMSG
DESCRIPTOR.message_types_by_name['BsfkMsg'] = _BSFKMSG

class BsTxMsg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class FwjqMsg(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _BSTXMSG_FWJQMSG

    # @@protoc_insertion_point(class_scope:BsTxMsg.FwjqMsg)

  class KfqqMsg(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _BSTXMSG_KFQQMSG

    # @@protoc_insertion_point(class_scope:BsTxMsg.KfqqMsg)
  DESCRIPTOR = _BSTXMSG

  # @@protoc_insertion_point(class_scope:BsTxMsg)

class BsfkMsg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BSFKMSG

  # @@protoc_insertion_point(class_scope:BsfkMsg)


# @@protoc_insertion_point(module_scope)
