# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smsTx.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='smsTx.proto',
  package='',
  serialized_pb='\n\x0bsmsTx.proto\"\x81\x01\n\x07\x42\x64\x66sMsg\x12\x11\n\tnSerialId\x18\x01 \x02(\r\x12\x16\n\x0enSourceAddress\x18\x02 \x02(\r\x12\x14\n\x0cnDestAddress\x18\x03 \x02(\r\x12\x10\n\x08nMsgType\x18\x04 \x02(\r\x12\x10\n\x08nInfoLen\x18\x05 \x02(\r\x12\x11\n\tsInfoBuff\x18\x06 \x02(\t\"*\n\x07\x46sfkMsg\x12\x11\n\tnSerialId\x18\x01 \x02(\r\x12\x0c\n\x04nRes\x18\x02 \x02(\r')




_BDFSMSG = _descriptor.Descriptor(
  name='BdfsMsg',
  full_name='BdfsMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nSerialId', full_name='BdfsMsg.nSerialId', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nSourceAddress', full_name='BdfsMsg.nSourceAddress', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nDestAddress', full_name='BdfsMsg.nDestAddress', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nMsgType', full_name='BdfsMsg.nMsgType', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nInfoLen', full_name='BdfsMsg.nInfoLen', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sInfoBuff', full_name='BdfsMsg.sInfoBuff', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=16,
  serialized_end=145,
)


_FSFKMSG = _descriptor.Descriptor(
  name='FsfkMsg',
  full_name='FsfkMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nSerialId', full_name='FsfkMsg.nSerialId', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nRes', full_name='FsfkMsg.nRes', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=147,
  serialized_end=189,
)

DESCRIPTOR.message_types_by_name['BdfsMsg'] = _BDFSMSG
DESCRIPTOR.message_types_by_name['FsfkMsg'] = _FSFKMSG

class BdfsMsg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BDFSMSG

  # @@protoc_insertion_point(class_scope:BdfsMsg)

class FsfkMsg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FSFKMSG

  # @@protoc_insertion_point(class_scope:FsfkMsg)


# @@protoc_insertion_point(module_scope)
